# Generated by Django 4.2.11 on 2024-04-24 07:20

import Admin_Login_App.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Technologies', models.CharField(max_length=150)),
                ('Images', models.ImageField(upload_to=Admin_Login_App.models.getFileName)),
                ('status', models.IntegerField(choices=[(0, 'enabled'), (1, 'disabled')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technologies', models.CharField(max_length=150)),
            ],
        ),
    ]
