# Generated by Django 4.2.11 on 2024-05-09 05:46

import Admin_Login_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(upload_to=Admin_Login_App.models.getlogo)),
                ('Job_Heading', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('No_Of_Openings', models.CharField(max_length=100)),
                ('Salary', models.FloatField()),
                ('Status', models.BooleanField(default=True)),
                ('Department', models.CharField(max_length=100)),
                ('Job_Type', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=255)),
                ('Job_Description', models.TextField()),
                ('Skills_Required', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
