# Generated by Django 4.2.11 on 2024-04-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0002_courses_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
