# Generated by Django 4.2.11 on 2024-05-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0002_careers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='Department',
        ),
    ]
