# Generated by Django 4.2.11 on 2024-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Login_App', '0005_blog_faq_placementstories_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners_logo',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
